services:
  - type: web
    name: sistema-automatico
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16